if [ -e ~/.nix-profile/etc/profile.d/nix.sh ]; then . ~/.nix-profile/etc/profile.d/nix.sh; fi # added by Nix installer

wsl_host_ip() {
    cat /etc/resolv.conf | grep nameserver | awk '{print $2; exit;}'
}

if [ -e ~/.zshrc_local ]; then . ~/.zshrc_local; fi
